### PR TITLE
README: tweaked contents

### PR DESCRIPTION
**Pull request by luzpaz**
* moved Installation section below Feature section  
* removed screenshot of addon manager
* replaced with link to addon manager
* removed superfluous words
* hid manual installation instructions in collapsed div
* substituted 'extension' for 'addon'

Preview: https://github.com/luzpaz/FreecadDiscordPresence/blob/README-tweak/README.md

### CODE REVIEW

**Comment by TzurSoffer** [comment]
I have redone many parts of the README.md, so I cannot merge this pull request. I have, however, taken some of your advice regarding the README, namely:

* replaced screenshot with link to addon manager
* moved Installation section below Feature section

Since this pull request will not be merged, I have credited you in the Credits section of the readme. If you have any suggestions or comments regarding this, please let me know.

**Comment by luzpaz** [comment]
I still suggest changing the verbiage from 'extension' to 'addon' 
JFYI, that the manual install is sort of obsolete now that addon manager can install the addon. So users who are viewing the workbench through the addon manager UI will be seeing it unnecessarily. Hence i put it into a collapsed div - to reduce clutter etc... this solution keeps it for posterity and as a workaround solution but ultimately I defer to your discretion.

**Comment by TzurSoffer** [comment]
I see, while I do not prefer collapsed containers normally, I did not account for the smaller viewing window of the FreeCAD addon manager. Thank you for telling me about it! I have modified the README.md as suggested as well as replaced instances of "extension" with "addon". Thank you once again for your help.

**Comment by luzpaz** [comment]
Just one last nit-pick: the [Dependencies](https://github.com/TzurSoffer/FreecadDiscordPresence?tab=readme-ov-file#dependencies) section. Should we fold that into the collapsed div or add a note informing the user that the installation of pypresence will be automated if they used the Addon Manager ?

**Comment by TzurSoffer** [comment]
Totally agree 👍. This has been changed.

**Pull request closed without merging**
